import io
import os
from datetime import datetime, timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
    Image, HRFlowable,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus.doctemplate import PageTemplate, BaseDocTemplate, Frame
from reportlab.platypus.frames import Frame


class NumberedCanvas:
    def __init__(self, doc):
        self.doc = doc

    def __call__(self, canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.grey)
        canvas.drawRightString(A4[0] - 20 * mm, 10 * mm, f"Page {doc.page}")
        canvas.drawString(20 * mm, 10 * mm, "Generated by SentinelAI")
        canvas.restoreState()


def build_pdf(report_data: dict, report_type: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=20 * mm, bottomMargin=20 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("ReportTitle", parent=styles["Title"], fontSize=24, spaceAfter=6, textColor=colors.HexColor("#00F5FF"))
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"], fontSize=12, spaceAfter=20, textColor=colors.grey)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"], fontSize=14, spaceAfter=10, textColor=colors.HexColor("#1a1a2e"))
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, spaceAfter=6, leading=14)
    label_style = ParagraphStyle("Label", parent=styles["Normal"], fontSize=9, textColor=colors.grey)
    value_style = ParagraphStyle("Value", parent=styles["Normal"], fontSize=12, spaceAfter=4)

    elements = []

    elements.append(Spacer(1, 40 * mm))
    elements.append(Paragraph("SENTINELAI", title_style))
    elements.append(Paragraph("Enterprise SOC Report", subtitle_style))
    elements.append(Spacer(1, 10 * mm))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#00F5FF")))
    elements.append(Spacer(1, 10 * mm))
    elements.append(Paragraph(f"Report Type: <b>{report_type.replace('_', ' ').title()}</b>", body_style))
    elements.append(Paragraph(f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", body_style))
    elements.append(Spacer(1, 5 * mm))
    elements.append(Paragraph("Confidential - For Authorized Personnel Only", label_style))
    elements.append(PageBreak())

    elements.append(Paragraph("Table of Contents", heading_style))
    elements.append(Spacer(1, 5 * mm))
    elements.append(Paragraph("1. Executive Summary", body_style))
    elements.append(Paragraph("2. Key Metrics", body_style))
    elements.append(Paragraph("3. Detailed Analysis", body_style))
    elements.append(Paragraph("4. Recommendations", body_style))
    elements.append(PageBreak())

    elements.append(Paragraph("1. Executive Summary", heading_style))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#00F5FF")))
    elements.append(Spacer(1, 5 * mm))

    if report_type == "executive":
        data = report_data
        elements.append(Paragraph(f"Total Incidents: <b>{data.get('total_incidents', 0)}</b>", body_style))
        elements.append(Paragraph(f"Critical Incidents: <b>{data.get('critical_incidents', 0)}</b>", body_style))
        elements.append(Paragraph(f"Resolved Incidents: <b>{data.get('resolved_incidents', 0)}</b>", body_style))
        elements.append(Paragraph(f"Open Incidents: <b>{data.get('open_incidents', 0)}</b>", body_style))
        elements.append(Spacer(1, 5 * mm))

        avg_resp = data.get("avg_response_time_seconds")
        if avg_resp:
            elements.append(Paragraph(f"Avg Response Time: <b>{avg_resp:.0f}s</b>", body_style))
        avg_resl = data.get("avg_resolution_time_seconds")
        if avg_resl:
            elements.append(Paragraph(f"Avg Resolution Time: <b>{avg_resl:.0f}s</b>", body_style))
        elements.append(Paragraph(f"SOC Health Score: <b>{data.get('soc_health_score', 0)}%</b>", body_style))

        if data.get("top_risks"):
            elements.append(Spacer(1, 5 * mm))
            elements.append(Paragraph("Top Risks:", heading_style))
            risk_data = [[Paragraph("Risk", label_style), Paragraph("Count", label_style)]]
            for r in data["top_risks"][:10]:
                risk_data.append([Paragraph(str(r.get("name", "")), body_style), Paragraph(str(r.get("count", 0)), body_style)])
            t = Table(risk_data, colWidths=[120 * mm, 40 * mm])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(t)

    elif report_type == "incident":
        data = report_data
        elements.append(Paragraph(f"<b>{data.get('incident_title', '')}</b>", body_style))
        elements.append(Paragraph(f"Severity: {data.get('severity', '')} | Status: {data.get('status', '')}", body_style))
        elements.append(Spacer(1, 3 * mm))
        elements.append(Paragraph(data.get("description", "No description"), body_style))

        if data.get("tasks"):
            elements.append(Spacer(1, 5 * mm))
            elements.append(Paragraph("Tasks:", heading_style))
            for t in data["tasks"]:
                status_icon = "+" if t.get("status") == "completed" else "o"
                elements.append(Paragraph(f"[{status_icon}] {t.get('title', '')} - {t.get('status', '')}", body_style))

        if data.get("ai_investigation"):
            elements.append(Spacer(1, 5 * mm))
            elements.append(Paragraph("AI Investigation Summary:", heading_style))
            ai = data["ai_investigation"]
            if ai.get("summary"):
                elements.append(Paragraph(ai["summary"], body_style))
            if ai.get("root_cause"):
                elements.append(Paragraph(f"Root Cause: {ai['root_cause']}", body_style))

    else:
        for key, value in report_data.items():
            if key in ("report_type", "generated_at", "date_range"):
                continue
            if isinstance(value, (str, int, float, bool)):
                elements.append(Paragraph(f"{key.replace('_', ' ').title()}: <b>{value}</b>", body_style))

    elements.append(Spacer(1, 10 * mm))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#00F5FF")))
    elements.append(Spacer(1, 5 * mm))
    elements.append(Paragraph("Generated by SentinelAI Enterprise SOC Platform", label_style))

    doc.build(elements, onFirstPage=NumberedCanvas(doc), onLaterPages=NumberedCanvas(doc))
    return buf.getvalue()
