from datetime import datetime, timezone

EMAIL_TEMPLATES: dict[str, str] = {}


def _base_html(body: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>SentinelAI Notification</title></head>
<body style="margin:0;padding:0;background-color:#0a0a0f;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#0a0a0f;">
<tr><td align="center" style="padding:40px 20px;">
<table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background-color:#1a1a2e;border-radius:12px;border:1px solid #00F5FF20;">
<tr><td style="padding:32px 40px;text-align:center;border-bottom:1px solid #00F5FF20;">
<img src="https://i.imgur.com/QsXoNtm.png" alt="SentinelAI" width="48" height="48" style="margin-bottom:8px;">
<h1 style="color:#00F5FF;font-size:22px;margin:0;font-weight:600;">SentinelAI</h1>
<p style="color:#888;font-size:12px;margin:4px 0 0;">Enterprise SOC Platform</p>
</td></tr>
<tr><td style="padding:32px 40px;">
{body}
</td></tr>
<tr><td style="padding:20px 40px;text-align:center;border-top:1px solid #00F5FF20;">
<p style="color:#555;font-size:11px;margin:0;">Generated by SentinelAI · {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</p>
<p style="color:#555;font-size:11px;margin:4px 0 0;">This is an automated notification. Do not reply.</p>
</td></tr>
</table>
</td></tr>
</table>
</body>
</html>"""


def render_email_template(template_name: str, context: dict) -> str:
    if template_name == "critical_incident":
        body = f"""
<h2 style="color:#EF4444;margin:0 0 16px;font-size:18px;">⚠ Critical Incident</h2>
<p style="color:#ccc;font-size:14px;line-height:1.6;">A new <strong style="color:#EF4444;">{context.get('severity', 'CRITICAL')}</strong> incident has been created:</p>
<div style="background:#0a0a0f;border-radius:8px;padding:16px;margin:16px 0;border:1px solid #EF444440;">
<p style="color:#fff;font-size:16px;margin:0 0 8px;"><strong>{context.get('title', '')}</strong></p>
<p style="color:#888;font-size:12px;margin:0;">ID: {context.get('incident_id', '')}</p>
</div>
<p style="color:#ccc;font-size:14px;">View in SentinelAI: <a href="#" style="color:#00F5FF;">Open Incident</a></p>"""
        return _base_html(body)

    if template_name == "critical_ioc":
        body = f"""
<h2 style="color:#EF4444;margin:0 0 16px;font-size:18px;">⚠ Critical IOC Detected</h2>
<div style="background:#0a0a0f;border-radius:8px;padding:16px;margin:16px 0;border:1px solid #EF444440;">
<p style="color:#fff;font-size:16px;margin:0 0 8px;"><strong>{context.get('ioc_value', '')}</strong></p>
<p style="color:#888;font-size:12px;margin:0;">Type: {context.get('ioc_type', '')}</p>
</div>"""
        return _base_html(body)

    if template_name == "threat_match":
        body = f"""
<h2 style="color:#F59E0B;margin:0 0 16px;font-size:18px;">Threat Intelligence Match</h2>
<div style="background:#0a0a0f;border-radius:8px;padding:16px;margin:16px 0;border:1px solid #F59E0B40;">
<p style="color:#fff;font-size:16px;margin:0 0 8px;"><strong>{context.get('ioc_value', '')}</strong></p>
<p style="color:#888;font-size:12px;margin:0;">Type: {context.get('threat_type', '')}</p>
</div>"""
        return _base_html(body)

    if template_name == "ai_complete":
        body = f"""
<h2 style="color:#10B981;margin:0 0 16px;font-size:18px;">AI Investigation Complete</h2>
<p style="color:#ccc;font-size:14px;line-height:1.6;">The AI investigation has finished for:</p>
<div style="background:#0a0a0f;border-radius:8px;padding:16px;margin:16px 0;border:1px solid #10B98140;">
<p style="color:#fff;font-size:16px;margin:0;"><strong>{context.get('incident_title', '')}</strong></p>
</div>"""
        return _base_html(body)

    if template_name == "daily_report":
        body = f"""
<h2 style="color:#00F5FF;margin:0 0 16px;font-size:18px;">Daily SOC Report</h2>
<p style="color:#ccc;font-size:14px;line-height:1.6;">Here is your daily summary of SOC activity.</p>
<div style="background:#0a0a0f;border-radius:8px;padding:16px;margin:16px 0;border:1px solid #00F5FF20;">
<p style="color:#888;font-size:12px;margin:0 0 8px;">Key Metrics</p>
<p style="color:#fff;font-size:14px;margin:0;">Total Incidents: <strong>{context.get('total_incidents', 'N/A')}</strong></p>
<p style="color:#fff;font-size:14px;margin:4px 0;">Critical: <strong style="color:#EF4444;">{context.get('critical', 'N/A')}</strong></p>
<p style="color:#fff;font-size:14px;margin:4px 0;">Resolved: <strong style="color:#10B981;">{context.get('resolved', 'N/A')}</strong></p>
</div>"""
        return _base_html(body)

    if template_name == "weekly_report":
        body = f"""
<h2 style="color:#00F5FF;margin:0 0 16px;font-size:18px;">Weekly SOC Report</h2>
<p style="color:#ccc;font-size:14px;line-height:1.6;">Your weekly security operations summary.</p>
<div style="background:#0a0a0f;border-radius:8px;padding:16px;margin:16px 0;border:1px solid #00F5FF20;">
<p style="color:#fff;font-size:14px;margin:0 0 8px;">Weekly Summary</p>
<p style="color:#888;font-size:12px;margin:0;">Total Incidents: {context.get('total_incidents', 'N/A')}</p>
<p style="color:#888;font-size:12px;margin:4px 0;">Critical: {context.get('critical', 'N/A')}</p>
<p style="color:#888;font-size:12px;margin:4px 0;">Resolved: {context.get('resolved', 'N/A')}</p>
</div>"""
        return _base_html(body)

    return _base_html(f"<p style='color:#ccc;font-size:14px;'>{template_name} notification</p>")
